# Generated by Django 2.0.3 on 2018-03-28 12:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(blank=True, max_length=95, null=True)),
                ('postcode', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999)])),
                ('street', models.CharField(blank=True, max_length=80, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'users',
                'verbose_name': 'user',
            },
        ),
    ]
